package(default_visibility = ["//java/com/google/turbine:__subpackages__"])

java_library(
    name = "sig",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/turbine/model",
        "@guava//jar",
        "@jsr305//jar",
    ],
)
