package(default_visibility = ["//java/com/google/turbine:__subpackages__"])

java_library(
    name = "options",
    srcs = glob(["*.java"]),
    deps = [
        "@guava//jar",
        "@jsr305//jar",
    ],
)
