package(default_visibility = ["//java/com/google/turbine:__subpackages__"])

java_library(
    name = "sym",
    srcs = glob(["*.java"]),
    deps = [
        "@error_prone_annotations//jar",
        "@guava//jar",
        "@jsr305//jar",
    ],
)
