package(default_visibility = ["//java/com/google/turbine:__subpackages__"])

java_library(
    name = "type",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/turbine/binder/sym",
        "//java/com/google/turbine/diag",
        "//java/com/google/turbine/model",
        "//java/com/google/turbine/tree",
        "@guava//jar",
    ],
)
