package(default_visibility = ["//java/com/google/turbine:__subpackages__"])

java_library(
    name = "parse",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/turbine/diag",
        "//java/com/google/turbine/model",
        "//java/com/google/turbine/tree",
        "@error_prone_annotations//jar",
        "@guava//jar",
        "@jsr305//jar",
    ],
)
