package(default_visibility = ["//java/com/google/turbine:__subpackages__"])

java_library(
    name = "env",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/turbine/binder/sym",
        "@guava//jar",
        "@jsr305//jar",
    ],
)
