package(default_visibility = ["//java/com/google/turbine:__subpackages__"])

java_library(
    name = "tree",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/turbine/diag",
        "//java/com/google/turbine/model",
        "@guava//jar",
    ],
)
