# Copyright 2020 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  test:
    name: "JDK ${{ matrix.java }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java: [ 26, 25 ]
        experimental: [ false ]
        include:
          # Only test on macos and windows with a single recent JDK to avoid a
          # combinatorial explosion of test configurations.
          - os: macos-latest
            java: 25
            experimental: false
          - os: windows-latest
            java: 25
            experimental: false
          - os: ubuntu-latest
            java: EA
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}
      - name: 'Check out repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: 'Set up JDK ${{ matrix.java }} from jdk.java.net'
        if: ${{ matrix.java == 'EA' }}
        uses: oracle-actions/setup-java@ec7274acdd237c7fe61395ed2edda22d756b5afe # v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
          cache: 'maven'
      - name: 'Set up JDK ${{ matrix.java }}'
        if: ${{ matrix.java != 'EA' }}
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - name: 'Install'
        shell: bash
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: 'Test'
        shell: bash
        run: mvn test -B
      - name: 'Javadoc'
        shell: bash
        run: mvn javadoc:aggregate
